### ISSUE TITLE
Optimized images not cached in CF

### ISSUE THREAD

**Issue by syphernl** [milliHQ/terraform-aws-next-js-image-optimization#135]
I am currently debugging complaints of slowness on our NextJS-based webapplication. 
A first thing I noticed that the images that are going through the Image Optimizer are always showing "MISS from Cloudfront".

Our "image request route" normally goes like this:
```
Client -> CF: https://assets.example.com/_next/image?url=https://assets.example.com/uploads/foo.jpg&w=320&q=75 -> API Gateway -> Image Optimizer Lambda -> CF: https://assets.example.com/uploads/foo.jpg -> S3 bucket
```
(The above url has not been urlencoded to make it more readable, in normal situations it is properly urlencoded)

This results in:
* Always a `MISS` when queried via the above route (with a `cache-control: public, max-age=0, must-revalidate`
* Always a  `MISS` when queried directly on `_next/image?` on the **API gateway** (bypassing the first pass of CF) (with `cache-control: public, max-age=0, must-revalidate`)
* `HIT` when the image URL (`https://assets.example.com/uploads/foo.jpg`) is queried directly (with no `cache-control` response header)

When querying the image directly via the S3 console I do _not_ see any Cache headers in the response either.

I'm not sure where this is going wrong. The CF settings seem to be fine, since querying the file directly (not via optimizer) shows HIT. 

The `/_next/image` behavior in CF has the following cache policy settings:
* Min TTL = `0`
* Max TTL = `31536000`
* Default TTL = `86400`
* Headers: `Accept`
* Cookies: `None`
* Query Strings: `q, w, url`
* Gzip: `Enabled`
* Brotli: `Enabled`

And origin request policy for behavior `/_next/image`:

* Headers: `Accept`
* Cookies: `None`
* Query Strings: `q, w, url`

For the `uploads/*` behavior we use "Legacy Settings" with Headers, Query Strings and Cookies all set to "None" and Object Caching set to "Use origin cache headers")

Based off this it appears  that the Lambda may not be setting the appropriate cache headers, which causes CF to skip caching it? If so, is there anything misconfigured on our end or could this be an issue in the Optimizer?

**Comment by ofhouse** [comment]
Hi, the cache control response that is issued by the image optimization API depends on the `Cache-Control` header that is sent by the original image source.

So in your case the image optimizer looks into the `Cache-Control` header that it receives from `https://assets.example.com/uploads/foo.jpg`:
- If a `Cache-Control` header is present on the response, it should copy the `max-age` value from it to the response of the image optimizer (Gets stored in CloudFront)
- If **no** `Cache-Control` header is present on this response, it defaults to `cache-control: public, max-age=0, must-revalidate` (Image gets optimized on every request, is not stored in CloudFront)

You can validate this by opening `https://assets.example.com/uploads/foo.jpg` in the browser, and check the response headers in the network tab of your devTools.

So my suggestion here is, that the `Cache-Control` metadata is not set on the images in the S3 bucket.

**Comment by syphernl** [comment]
Thanks @ofhouse for your quick and expansive reply 😄 
We indeed did not have `Cache-Control` on the assets in the S3 bucket. 

I have solved this by adding a Response Header Policy to the CF distribution, which means that any asset served that does not have `Cache-Control` header gets one added anyway. And if the asset has a different setting it will be used instead. This seems to work pretty well. The cache now gets hit when we request an optimized image.

However, one thing I noticed is that I set the following on the assets served to the optimizer:

```
cache-control: public,max-age=31536000,immutable
```

Yet the optimizer itself produces:

```
cache-control: public, max-age=31536000, must-revalidate
```

Which is a bit odd because it [appears to be](https://github.com/milliHQ/terraform-aws-next-js-image-optimization/blob/main/lib/image-optimizer.ts#L80-L83) copying the entire cache-control header.

**Comment by ofhouse** [comment]
> Which is a bit odd because it [appears to be](https://github.com/milliHQ/terraform-aws-next-js-image-optimization/blob/main/lib/image-optimizer.ts#L80-L83) copying the entire cache-control header.

I agree, but this behaviour is intentional:
The Next.js image optimizer internally always uses a HTTP request to obtain the original image, as it has no native support for S3.
So what we do inside of this module is to mock the outgoing HTTP request, send a fake response with with the data (body and `Cache-Control` metadata) from S3 and give it back to the optimizer.
This way the optimizer works with it as the image would be fetched over HTTP (and not from S3).

However we have no control on how the image optimizer generates the `Cache-Control` response header, because this happens after the step described above.
It parses the values from the source `Cache-Control` header and then creates a new value for the header: https://github.com/vercel/next.js/blob/canary/packages/next/server/image-optimizer.ts#L575-L580

Since we don't aim to modify the original behaviour of the Next.js image optimizer in this project (Response should always be the same as when you host Next.js in a docker environment or on Vercel), the only way to solve this would be to create a feature request on the Next.js project.

**Comment by ofhouse** [comment]
I'm going to close this issue because it has been inactive for 30 days ⏳. This helps to find and focus on the active issues.
