### ISSUE TITLE
QUESTION: Ordered cache behaviours on existing CF distribution

### ISSUE THREAD

**Issue by gianpaolom** [milliHQ/terraform-aws-next-js-image-optimization#99]
I am using the module with an already existing CF distribution, as I want to have a custom domain for the CDN with its own SSL certificate.
The distribution already has its own default cache behaviours, and I see in the existing example, there is a dynamic block added for the default behaviour.
However I would like to be able to fetch other static assets through the CDN that are not images, so having the default behaviour triggering the lambda is not ideal.
Is it possible to add the dynamic with this module settings on an ordered cache behaviour using the `/_next/image/*` as path?

**Comment by gianpaolom** [comment]
@ofhouse awesome! Thanks for the prompt reply :)

**Comment by ofhouse** [comment]
I'm going to close this issue because it has been inactive for 30 days ⏳. This helps to find and focus on the active issues.
